### PR TITLE
Download NCBI Taxdmp file in CI

### PR DESCRIPTION
**Pull request by stijndcl**
We discussed adding this file to the automatic releases because it is sometimes arbitrarily slow to download

### CODE REVIEW

**Review by pverscha — CHANGES_REQUESTED** [review]
This looks good. Can you update the `build_database`-script accordingly such that it uses our mirrored version of the taxon dump? Ideally the script should check if our "mirrored version" is available, and automatically fallback to the old URL if not.

**Comment by stijndcl** [comment]
Will do. I didn't do it yet for now because the very first time the file will not exist, but using the default as a fallback is a good idea and fixes that problem as well.

**Comment by stijndcl** [comment]
Very ironically showing that this is already a good change, NCBI just changed their endpoint and the original download URL no longer works.

**Review by pverscha — APPROVED** [review]
Thanks! This code looks great as well :) I'll start the run to create a new version of the static database (and upload our new taxon file) right now.

**Pull request merged**
